// BMP decoding ported from stb_image.h v2.30 by Sean Barrett and contributors
// (https://github.com/nothings/stb), dual-licensed public domain (unlicense) / MIT.
// The port reproduces stb_image's output bit-exactly for stbi_load_from_memory(..., desired_channels: 3).

namespace SentenceTransformers.EmbeddingGemma2.Vision;

/// <summary>
/// Pure-managed port of stb_image's BMP decoder (<c>stbi__bmp_load</c>): uncompressed 1/4/8-bit
/// paletted, 16/24/32-bit (including BI_BITFIELDS masks), OS/2 and V3/V4/V5 headers, bottom-up and
/// top-down row order. RLE and embedded JPEG/PNG compression are rejected, as in stb.
/// </summary>
internal static class BmpDecoder
{
    /// <summary>STBI_MAX_DIMENSIONS.</summary>
    private const uint MaxDimensions = 1u << 24;

    /// <summary>stbi__bmp_test: "BM" followed by a known info-header size.</summary>
    public static bool IsBmp(ReadOnlySpan<byte> data)
    {
        var s = new Reader(data);
        if (s.Get8() != 'B' || s.Get8() != 'M')
        {
            return false;
        }
        s.Get32Le(); // file size
        s.Get16Le(); // reserved
        s.Get16Le(); // reserved
        s.Get32Le(); // data offset
        uint sz = s.Get32Le();
        return sz == 12 || sz == 40 || sz == 56 || sz == 108 || sz == 124;
    }

    /// <summary>
    /// Decodes a BMP to packed RGB (3 bytes per pixel, row-major, top row first).
    /// </summary>
    /// <exception cref="InvalidDataException">The stream is not a BMP stb_image can decode.</exception>
    public static byte[] Decode(ReadOnlySpan<byte> data, out int width, out int height)
    {
        var s = new Reader(data);

        // ---- stbi__bmp_parse_header ----
        if (s.Get8() != 'B' || s.Get8() != 'M')
        {
            throw Corrupt("not BMP");
        }
        s.Get32Le(); // discard filesize
        s.Get16Le(); // discard reserved
        s.Get16Le(); // discard reserved
        int offset = (int)s.Get32Le();
        int hsz = (int)s.Get32Le();
        uint mr = 0, mg = 0, mb = 0, ma = 0;
        int extraRead = 14;

        if (offset < 0)
        {
            throw Corrupt("bad BMP");
        }
        if (hsz != 12 && hsz != 40 && hsz != 56 && hsz != 108 && hsz != 124)
        {
            throw new InvalidDataException("BMP type not supported: unknown");
        }
        uint imgX, imgY;
        if (hsz == 12)
        {
            imgX = (uint)s.Get16Le();
            imgY = (uint)s.Get16Le();
        }
        else
        {
            imgX = s.Get32Le();
            imgY = s.Get32Le();
        }
        if (s.Get16Le() != 1)
        {
            throw Corrupt("bad BMP");
        }
        int bpp = s.Get16Le();
        if (hsz != 12)
        {
            int compress = (int)s.Get32Le();
            if (compress == 1 || compress == 2)
            {
                throw new InvalidDataException("BMP type not supported: RLE");
            }
            if (compress >= 4)
            {
                throw new InvalidDataException("BMP type not supported: unsupported compression");
            }
            if (compress == 3 && bpp != 16 && bpp != 32)
            {
                throw Corrupt("bad BMP");
            }
            s.Get32Le(); // discard sizeof
            s.Get32Le(); // discard hres
            s.Get32Le(); // discard vres
            s.Get32Le(); // discard colorsused
            s.Get32Le(); // discard max important
            if (hsz == 40 || hsz == 56)
            {
                if (hsz == 56)
                {
                    s.Get32Le();
                    s.Get32Le();
                    s.Get32Le();
                    s.Get32Le();
                }
                if (bpp == 16 || bpp == 32)
                {
                    if (compress == 0)
                    {
                        SetMaskDefaults(bpp, compress, ref mr, ref mg, ref mb, ref ma);
                    }
                    else if (compress == 3)
                    {
                        mr = s.Get32Le();
                        mg = s.Get32Le();
                        mb = s.Get32Le();
                        extraRead += 12;
                        // not documented, but generated by photoshop and handled by mspaint
                        if (mr == mg && mg == mb)
                        {
                            throw Corrupt("bad BMP");
                        }
                    }
                    else
                    {
                        throw Corrupt("bad BMP");
                    }
                }
            }
            else
            {
                // V4/V5 header
                mr = s.Get32Le();
                mg = s.Get32Le();
                mb = s.Get32Le();
                ma = s.Get32Le();
                if (compress != 3)
                {
                    // override mr/mg/mb unless in BI_BITFIELDS mode, as per docs
                    SetMaskDefaults(bpp, compress, ref mr, ref mg, ref mb, ref ma);
                }
                s.Get32Le(); // discard color space
                for (int i = 0; i < 12; ++i)
                {
                    s.Get32Le(); // discard color space parameters
                }
                if (hsz == 124)
                {
                    s.Get32Le(); // discard rendering intent
                    s.Get32Le(); // discard offset of profile data
                    s.Get32Le(); // discard size of profile data
                    s.Get32Le(); // discard reserved
                }
            }
        }

        // ---- stbi__bmp_load ----
        bool flipVertically = (int)imgY > 0;
        if ((int)imgY == int.MinValue)
        {
            throw new InvalidDataException("Very large image (corrupt?)");
        }
        imgY = (uint)Math.Abs((int)imgY);
        if (imgY > MaxDimensions || imgX > MaxDimensions)
        {
            throw new InvalidDataException("Very large image (corrupt?)");
        }
        int w = (int)imgX, h = (int)imgY;

        int psize = 0;
        if (hsz == 12)
        {
            if (bpp < 24)
            {
                psize = (offset - extraRead - 24) / 3;
            }
        }
        else
        {
            if (bpp < 16)
            {
                psize = (offset - extraRead - hsz) >> 2;
            }
        }
        if (psize == 0)
        {
            // accept some extra bytes after the header, but reject offsets before the header end or far beyond it
            int bytesReadSoFar = s.Pos;
            if (bytesReadSoFar <= 0 || bytesReadSoFar > 1024)
            {
                throw Corrupt("bad header");
            }
            if (offset < bytesReadSoFar || offset - bytesReadSoFar > 256 * 4)
            {
                throw Corrupt("bad offset");
            }
            s.Skip(offset - bytesReadSoFar);
        }

        const int Target = 3;
        if ((long)w * h * Target > Math.Min(int.MaxValue, Array.MaxLength))
        {
            throw Corrupt("too large");
        }
        var output = new byte[w * h * Target];
        int z = 0;
        if (bpp < 16)
        {
            if (psize == 0 || psize > 256)
            {
                throw Corrupt("invalid");
            }
            Span<byte> pal = stackalloc byte[256 * 4];
            pal.Clear();
            for (int i = 0; i < psize; ++i)
            {
                pal[i * 4 + 2] = s.Get8();
                pal[i * 4 + 1] = s.Get8();
                pal[i * 4 + 0] = s.Get8();
                if (hsz != 12)
                {
                    s.Get8();
                }
                pal[i * 4 + 3] = 255;
            }
            s.Skip(offset - extraRead - hsz - psize * (hsz == 12 ? 3 : 4));
            int rowBytes;
            if (bpp == 1)
            {
                rowBytes = (w + 7) >> 3;
            }
            else if (bpp == 4)
            {
                rowBytes = (w + 1) >> 1;
            }
            else if (bpp == 8)
            {
                rowBytes = w;
            }
            else
            {
                throw Corrupt("bad bpp");
            }
            int pad = (-rowBytes) & 3;
            if (bpp == 1)
            {
                for (int j = 0; j < h; ++j)
                {
                    int bitOffset = 7, v = s.Get8();
                    for (int i = 0; i < w; ++i)
                    {
                        int c = ((v >> bitOffset) & 1) * 4;
                        output[z++] = pal[c];
                        output[z++] = pal[c + 1];
                        output[z++] = pal[c + 2];
                        if (i + 1 == w)
                        {
                            break;
                        }
                        if (--bitOffset < 0)
                        {
                            bitOffset = 7;
                            v = s.Get8();
                        }
                    }
                    s.Skip(pad);
                }
            }
            else
            {
                for (int j = 0; j < h; ++j)
                {
                    for (int i = 0; i < w; i += 2)
                    {
                        int v = s.Get8(), v2 = 0;
                        if (bpp == 4)
                        {
                            v2 = v & 15;
                            v >>= 4;
                        }
                        output[z++] = pal[v * 4];
                        output[z++] = pal[v * 4 + 1];
                        output[z++] = pal[v * 4 + 2];
                        if (i + 1 == w)
                        {
                            break;
                        }
                        v = bpp == 8 ? s.Get8() : v2;
                        output[z++] = pal[v * 4];
                        output[z++] = pal[v * 4 + 1];
                        output[z++] = pal[v * 4 + 2];
                    }
                    s.Skip(pad);
                }
            }
        }
        else
        {
            int rshift = 0, gshift = 0, bshift = 0, rcount = 0, gcount = 0, bcount = 0;
            int easy = 0;
            s.Skip(offset - extraRead - hsz);
            int rowBytes = bpp == 24 ? 3 * w : bpp == 16 ? 2 * w : 0;
            int pad = (-rowBytes) & 3;
            if (bpp == 24)
            {
                easy = 1;
            }
            else if (bpp == 32)
            {
                if (mb == 0xff && mg == 0xff00 && mr == 0x00ff0000 && ma == 0xff000000)
                {
                    easy = 2;
                }
            }
            if (easy == 0)
            {
                if (mr == 0 || mg == 0 || mb == 0)
                {
                    throw Corrupt("bad masks");
                }
                // right shift amount to put the high bit in position #7
                rshift = HighBit(mr) - 7;
                rcount = BitCount(mr);
                gshift = HighBit(mg) - 7;
                gcount = BitCount(mg);
                bshift = HighBit(mb) - 7;
                bcount = BitCount(mb);
                int acount = BitCount(ma);
                if (rcount > 8 || gcount > 8 || bcount > 8 || acount > 8)
                {
                    throw Corrupt("bad masks");
                }
            }
            for (int j = 0; j < h; ++j)
            {
                if (easy != 0)
                {
                    for (int i = 0; i < w; ++i)
                    {
                        output[z + 2] = s.Get8();
                        output[z + 1] = s.Get8();
                        output[z + 0] = s.Get8();
                        z += 3;
                        if (easy == 2)
                        {
                            s.Get8(); // alpha (dropped)
                        }
                    }
                }
                else
                {
                    for (int i = 0; i < w; ++i)
                    {
                        uint v = bpp == 16 ? (uint)s.Get16Le() : s.Get32Le();
                        output[z++] = (byte)ShiftSigned(v & mr, rshift, rcount);
                        output[z++] = (byte)ShiftSigned(v & mg, gshift, gcount);
                        output[z++] = (byte)ShiftSigned(v & mb, bshift, bcount);
                    }
                }
                s.Skip(pad);
            }
        }

        if (flipVertically)
        {
            int rowLen = w * Target;
            var tmp = new byte[rowLen];
            for (int j = 0; j < h >> 1; ++j)
            {
                Span<byte> p1 = output.AsSpan(j * rowLen, rowLen);
                Span<byte> p2 = output.AsSpan((h - 1 - j) * rowLen, rowLen);
                p1.CopyTo(tmp);
                p2.CopyTo(p1);
                tmp.CopyTo(p2);
            }
        }

        width = w;
        height = h;
        return output;
    }

    private static InvalidDataException Corrupt(string why) => new("Corrupt BMP: " + why);

    /// <summary>stbi__bmp_set_mask_defaults (alpha bookkeeping omitted: RGB output drops alpha).</summary>
    private static void SetMaskDefaults(int bpp, int compress, ref uint mr, ref uint mg, ref uint mb, ref uint ma)
    {
        if (compress == 3)
        {
            return;
        }
        if (compress == 0)
        {
            if (bpp == 16)
            {
                mr = 31u << 10;
                mg = 31u << 5;
                mb = 31u << 0;
            }
            else if (bpp == 32)
            {
                mr = 0xffu << 16;
                mg = 0xffu << 8;
                mb = 0xffu << 0;
                ma = 0xffu << 24;
            }
            else
            {
                mr = mg = mb = ma = 0;
            }
        }
    }

    /// <summary>stbi__high_bit: index of the highest set bit, -1 for 0.</summary>
    private static int HighBit(uint z) => z == 0 ? -1 : 31 - System.Numerics.BitOperations.LeadingZeroCount(z);

    /// <summary>stbi__bitcount.</summary>
    private static int BitCount(uint a) => System.Numerics.BitOperations.PopCount(a);

    /// <summary>stbi__shiftsigned: extract an arbitrarily aligned field and extend it to 8 bits.</summary>
    private static int ShiftSigned(uint v, int shift, int bits)
    {
        ReadOnlySpan<uint> mulTable = [0, 0xff, 0x55, 0x49, 0x11, 0x21, 0x41, 0x81, 0x01];
        ReadOnlySpan<int> shiftTable = [0, 0, 0, 1, 0, 2, 4, 6, 0];
        if (shift < 0)
        {
            v <<= -shift;
        }
        else
        {
            v >>= shift;
        }
        v >>= 8 - bits;
        return (int)(v * mulTable[bits]) >> shiftTable[bits];
    }

    /// <summary>Sequential little-endian reader with stb's memory-context semantics (reads past the end return 0).</summary>
    private ref struct Reader
    {
        private readonly ReadOnlySpan<byte> _data;
        public int Pos;

        public Reader(ReadOnlySpan<byte> data)
        {
            _data = data;
            Pos = 0;
        }

        public byte Get8() => Pos < _data.Length ? _data[Pos++] : (byte)0;

        public int Get16Le()
        {
            int z = Get8();
            return z + (Get8() << 8);
        }

        public uint Get32Le()
        {
            uint z = (uint)Get16Le();
            return z + ((uint)Get16Le() << 16);
        }

        /// <summary>stbi__skip: negative or out-of-range skips land at the end of the buffer.</summary>
        public void Skip(int n)
        {
            if (n == 0)
            {
                return;
            }
            Pos = n < 0 || n > _data.Length - Pos ? _data.Length : Pos + n;
        }
    }
}
