using System.Numerics;

namespace SentenceTransformers.EmbeddingGemma2.Numerics;

/// <summary>
/// Software emulation of the AVX-512 <c>vrsqrt14ss</c> reciprocal square root estimate, so that
/// <see cref="Xnn.ReciprocalSqrt"/> (and with it every RMSNorm) produces the same bits on CPUs without AVX-512
/// as XNNPACK's AVX-512 kernel does on CPUs with it.
/// <para>
/// The instruction's result depends only on the parity of the input exponent and the top 15 bits of its
/// mantissa (plus an exact result for powers of four), and has a 16-bit mantissa. Intel documents the error
/// bound but not a closed formula, so the 2 × 32768 table below was measured exhaustively on Intel AVX-512
/// hardware and verified against the instruction for every 32-bit input. It is stored as 2-bit decrements
/// between consecutive entries (the table is monotonically decreasing by 0-3 per step).
/// </para>
/// </summary>
internal static class Rsqrt14
{
    private const int Entries = 1 << 15;
    private const int OddExponentStart = 27141;   // rsqrt(0.5 · 1.f) ∈ (1, √2]: mantissa of the first entry
    private const int EvenExponentStart = 65530;  // rsqrt(1.f) ∈ (1/√2, 1): mantissa of the first entry (×2)

    private static readonly ushort[] OddTable = new ushort[Entries];
    private static readonly ushort[] EvenTable = new ushort[Entries];

    static Rsqrt14()
    {
        var packed = Convert.FromBase64String(Packed);
        int code = 0;
        int Next() => (packed[code >> 2] >> ((code++ & 3) * 2)) & 3;
        OddTable[0] = OddExponentStart;
        for (int i = 1; i < Entries; i++)
        {
            OddTable[i] = (ushort)(OddTable[i - 1] - Next());
        }
        EvenTable[0] = EvenExponentStart;
        for (int i = 1; i < Entries; i++)
        {
            EvenTable[i] = (ushort)(EvenTable[i - 1] - Next());
        }
    }

    /// <summary>The value <c>vrsqrt14ss</c> returns for <paramref name="a"/> (MXCSR.DAZ clear, as in .NET).</summary>
    public static float Estimate(float a)
    {
        uint bits = BitConverter.SingleToUInt32Bits(a);
        uint sign = bits >> 31;
        int exp = (int)((bits >> 23) & 0xFF);
        uint frac = bits & 0x7FFFFF;
        if (exp == 0xFF)
        {
            if (frac != 0)
            {
                return BitConverter.UInt32BitsToSingle(bits | 0x400000);   // quiet the NaN
            }
            return sign != 0 ? float.NaN : 0f;                               // rsqrt(-inf) = NaN, rsqrt(+inf) = +0
        }
        if (exp == 0)
        {
            if (frac == 0)
            {
                return sign != 0 ? float.NegativeInfinity : float.PositiveInfinity;
            }
            // Denormal: normalize (the estimate is computed on the exact value).
            int shift = BitOperations.LeadingZeroCount(frac) - 8;
            frac = (frac << shift) & 0x7FFFFF;
            exp = 1 - shift;
        }
        if (sign != 0)
        {
            return float.NaN;
        }
        int e = exp - 127;   // a = 2^e · 1.frac
        uint result;
        if ((e & 1) == 0)
        {
            // a = 4^(e/2) · 1.frac, rsqrt(1.frac) ∈ (1/√2, 1], exact for frac = 0.
            result = frac == 0
                ? (uint)(127 - e / 2) << 23
                : ((uint)(126 - e / 2) << 23) | ((uint)EvenTable[frac >> 8] << 7);
        }
        else
        {
            // a = 4^((e + 1)/2) · 0.5 · 1.frac, rsqrt(0.5 · 1.frac) ∈ (1, √2].
            result = ((uint)(127 - (e + 1) / 2) << 23) | ((uint)OddTable[frac >> 8] << 7);
        }
        return BitConverter.UInt32BitsToSingle(result);
    }

    private const string Packed =
        "llmWWZZZZllmWWaZZZllmWWWZZZlllmWWZZZZllmWWaZZZllmWWWZZZlllmWWZZZZllmWWaZZZllmWWWZZZlllmWWZZZZllmWWaZZZllmWWWZZZl" +
        "llmWWZZZZllmWWZZZpllmWWZZZZllmWWWZZZlllmWWZZZpllmWWZZZZllmWWWZZZlllmWWZZZpllmWWZZZZllmWWWZZZlllmWWZZZpllmWWZZZZl" +
        "lmWWWZZZlllmWWZZZpllmWWZZZZllmWWWZZZlllmWWZZZpllmWWZZZZllmWWWZZZlllmWWZZZllmmWWZZZlllmWWZZZZllmWWWZZZllmmWWZZZll" +
        "lmWWpZaVZVmWZVlZlmVZlpVlWZZlWVmWZVmWlWVZlmVZWZZlWZZlZVmWZVlWlmVZlmVlWZZlWVaWZVmWZWVZlmVZVpZlWZZlZVmWZVlWlmVZlmVl" +
        "WZZlWVaWZVmWZWVZlmVZVpZlWZZlWVmWZVmWlWVZlmVZWZZlWZaVZVmWZVlZlmVZlpVlWZZlWVmWZVmWlWVZlmVZWZZlWZaVZVmWZVlZlmVZlmVl" +
        "WZZlWVaWZVmWZWVZlmVZVpZlWZZlZVmWZVlWlmVZlmVlWZZlWVaWZVmWZWVZlmVZVpZlWZZlZVmWZVlWlmVZlmVZWZZlWZaVZVmWZVlZlmVZlpVl" +
        "WZZlWVmWZZmWlZWVZWVlZWVZWVlZWVZWVlaWlZWVlWVlZWVZWVlZWVZWVlaWlZWVlWVlZWVlWVlZWVlWVlaWlZWVlWVlZWVlWVlZWVlWVlZWlpWV" +
        "lWVlZWVlWVlZWVlWVlZWlpWVlZVlZWVlZVlZWVlWVlZWlpWVlZVlZWVlZVlZWVlZVlZWVpaVlZVlZWVlZVlZWVlZVlZWVpaVlZWVZWVlZVlZWVlZ" +
        "VlZWVpaVlZWVZWVlZWVZWVlZWVZWVpaVlZWVZWVlZWVZWVlZWVZWVlaWlZWVZWVlZWVZWVlZWVZWVlaWlZWVlWVlZWVlWVlZWVZWVlaWlZWVlWVl" +
        "ZWVlWVlZWVlWVlZWVlZZZZWVVVZZZZWVVVZZZWWVVVZZZWWVVVZZZWWVVVZZWWWVVVZZWWWVVVZZWWWVVVZWWWWVVVZWWWWVVVZWWWWVlVVWWWWV" +
        "lVVWWWWVlVVWWWVllVVWWWVllVVWWWVllVVWWVlllVVWWVlllVVWWVlllVVWVllllVVWVllllVVWVllllZVVVllllZVVVlllZZVVVlllZZVVVlll" +
        "ZZVVVllZZZVVVllZZZVVVllZZZVVVlZZZZVVVlZZZZVVVlZZZZWVVVZZZZWVVVZZZZWVVVZZZWWVVVZZZWWVVVZZZWWVVVZZWWWVVVZZWWWVVVZZ" +
        "WWWVVVZWWWWVVVZWWWWVVVZlVVZlVVZlVVmVVVmVVVmVVWVVVmVVVmVVVpVVWZVVWZVVWVVWZVVWZVVWZVVZlVVZlVVZlVVlVVZlVVZlVVaVVVmV" +
        "VVmVVVlVVmVVVmVVVmVVWZVVWZVVWZVVZVVWZVVWZVVWlVVZlVVZlVVZVVZlVVZlVVZlVVmVVVmVVVlVVmVVVmVVVmVVWZVVWZVVWZVVZVVWZVVW" +
        "ZVVWlVVZlVVZlVVZVVZlVVZlVVZlVVmVVVmVVVmVVWVVVmVVVmVVVpVVWZVVWZVVWVVWZVVWZVVWZVVZlVVZlVVZlVVlVVZlVVZlVVaVVVmVVVmV" +
        "VVlVVmVVVmVVVmVVWZVVWZVVWVVVZVWVVZVVVVZVWVVZVWVVlVWVVVVWVVlVWVVlVZVVVVZVVlVZVWVVZVWVVVVWVVZVWVVlVWVVlVVVVlVWVVlV" +
        "ZVVlVZVVVVZVVlVZVWVVZVWVVVVWVVZVWVVlVWVVlVVVVlVZVVlVZVWVVZVVVVZVWVVZVWVVlVWVVVVWVVlVWVVlVZVVlVVVVlVZVVlVZVWVVZVV" +
        "VVZVWVVZVWVVlVVVVlVWVVlVZVVlVZVVVVZVVlVZVWVVZVWVVVVWVVZVWVVlVWVVlVVVVlVWVVlVZVVlVZVVVVZVVlVZVWVVZVWVVVVWVVlVWVVl" +
        "VZVVlVVVVlVZVVlVZVWVVZVVVVZVWVUZlVVVVVlVVZVVVVVWVVVlVVVVVlVVZVVVVVZVVWVVVVVWVVVZVVWVVVVVWVVVlVVVVVlVVZVVVVVWVVVl" +
        "VVVVVlVVZVVVVVZVVWVVVZVVVVVZVVWVVVVVWVVVlVVVVVlVVWVVVVVWVVVlVVVVVlVVZVVVVVZVVVlVVZVVVVVZVVWVVVVVWVVVlVVVVVZVVWVV" +
        "VVVWVVVlVVVVVlVVZVVVVVZVVVlVVZVVVVVZVVWVVVVVWVVVlVVVVVZVVWVVVVVWVVVlVVVVVlVVZVVVlVVVVVlVVZVVVVVZVVWVVVVVWVVVZVVV" +
        "VVZVVWVVVVVWVVVlVVVVVlVVWVVVlVVVVVlVVVVVVlVVVVVVVVVlVVVVVVVVVVVWVVVVVVVVVWVVVVVVVVVVVVlVVVVVVVVVlVVVVVVVVVVVWVVV" +
        "VVVVVVWVVVVVVVVVVVVZVVVVVVVVVZVVVVVVVVVVVVlVVVVVVVVVVVZVVVVVVVVVZVVVVVVVVVVVVlVVVVVVVVVlVVVVVVVVVVVWVVVVVVVVVWVV" +
        "VVVVVVVVVVZVVVVVVVVVZVVVVVVVVVVVWVVVVVVVVVWVVVVVVVVVVVVZVVVVVVVVVZVVVVVVVVVVVVlVVVVVVVVVlVVVVVVVVVVVWVVVVVVVVVVV" +
        "VlVVVVVVVVVlVVVVVVVVVVVWVVVVVVVVVWVVVVVVVZVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVFVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVRVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVRVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVFVVVVVVVVVVVUVVUVVVVVVVUVVVVVVVUVVVVVVVRVVVVVVVRVVVVVVVRVVVVVVVVVUVVVVVVVUVVVV" +
        "VVVRVVVVVVVRVVVVVVVRVVVVVVVFVVVVVVVFVVVVVVUVVVVVVVUVVVVVVVUVVVVVVVVVVFVVVVVVVFVVVVVVVFVVVVVVUVVVVVVVUVVVVVVVRVVV" +
        "VVVVRVVVVVVVRVVVVVVVFVVVVVVVFVVVVVVVFVVVVVVVVVRVVVVVVVRVVVVVVVFVVVVVVVFVVVVVVVFVVVVVVUVVVVVVVUVVVVVVVRVVVVVVVRVV" +
        "VVVVVRVVVVVVVVVUVVVVVVVUVVVVVVVUVVVVVVVRVVVVVVVRVVVVFVVVUVVVRVVVVVRVVVFVVUVVVRVVVVVUVVVRVVVFVVUVVVVVUVVVRVVVFVVV" +
        "VVRVVVFVVUVVVRVVVVVRVVVFVVUVVVVVVFVVUVVVRVVVFVVVVVRVVUVVVRVVVVVUVVVRVVVFVVUVVVVVVFVVUVVVFVVVVVRVVVFVVUVVVRVVVVVU" +
        "VVVRVVVFVVVVVFVVUVVVRVVVFVVVVVRVVVFVVUVVVRVVVVVRVVVFVVUVVVVVVFVVUVVVRVVVFVVVVVFVVUVVVRVVVVVUVVVRVVVFVVUVVVVVVFVV" +
        "RVVVFVVVVVRVVVFVVUVVVRVVVVVUVVVRVVUVVVVVVFVVUVVVRVVVFVVVVVRVRVVVVFVRVUVVVVRVUVVFVVVUVVFVRVVVVFVRVUVVFVVVUVVFVRVV" +
        "VVFVRVUVVVVRVUVVFVVVUVVFVRVVVVFVRVUVVVVUVUVVFVVVVFVFVRVVVVRVRVUVVVVUVUVVFVVVVFVRVRVVVVRVUVUVVVVUVVFVFVVVVFVRVRVV" +
        "VVRVUVVFVVVUVVFVRVVVVFVRVUVVVVRVUVVFVVVUVVFVRVUVVVVRVUVVFVVVUVVFVRVVVVFVRVUVVVVRVUVVFVVVUVVFVRVVVVRVRVUVVVVUVUVV" +
        "FVVVVFVFVRVVVVRVRVUVVVVUVVFVFVVVVFVRVRVVVVRVUVUVVVVUVVFVFVVVVFVRVVFVVBVVFVVFVVFVVBVVFVVFVVFVVBVVFVVFVVFVVBVVFVVF" +
        "VVFVVFVUFVVFVVFVVFVUFVVFVVFVVFVUFVVFVVFVUVVUFVVFVVFVUVVUFVVFVVFVUVVUFVVFVVFVUVVUFVVFVUVVUVVUFVVFVUVVUVVUFVVFVUVV" +
        "UVVUFVVFVUVVUVVUFVUVVUVVUVVUFVUVVUVVUVVUFVUVVUVVUVVUFVUVVUVVUVVUVVQVVUVVUVVUVVQVVUVVUVVUVVQVVUVVUVVRVVQVVUVVUVVR" +
        "VVQVVUVVUVVRVVQVVUVVUVVRVVQVVUVVRVVRVVQVVUVVRVVRVVQVVUVVRVVRVVQVVUVVhRVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVV" +
        "URVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVVRVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVVURVVU" +
        "RVVURVVURVVURVVUFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVFVVRFVVRF" +
        "VVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVRFVVQVVVFFFVVUUUVVVFFFFVVUURVVVFFFFVVURRVV" +
        "VFFFFVVRRRVVVFEVVVRRRRVVVEUVVVRRRRVVUUUVVVRRRVVUUUUVVVRRFVVUUUUVVVFFFVVUUUVVVFFFFVVUURVVVFFFFVVURRVVVFFFFVVRRRVV" +
        "VFFFVVRRRRVVVEUVVVRRRRVVUUUVVVRRRVVUUUUVVVRRFVVUUUUVVVRFFVVUUUUVVVFFFVVUURVVVFFFFVVURRVVVFFFFVVRRRVVVFFFVVRRRRVV" +
        "VFEVVVRRRRVVUUUVVVRRRVVUUUUVVVRRFVVUUUUVVVRFFVVUUUUVVVFFFVVUUUVVVFFFFVVURRVVVFFFUVFFRRVVVFRRRUUVFVVUUVFFRRVVVFRR" +
        "RUUVFVVUUVFFRRVVVFRRUUUVFVVUUVFFRRVVVFRRUUUVFVVUUVFFRRVVVFRRUUUVFVVUVFFFRRVVVFRRUUUVFVVUVFFFRRUVVVRRUUUVFVVUVFFF" +
        "RRUVVVRRUUUVFVVUVFFFRRUVVVRRUUVFFVVUVFFFRRUVVVRRUUVFFVVUVFFFRRUVVVRRUUVFFVVUVFFRRRUVVVRRUUVFFVVUVFFRRRUVVVRRUUVF" +
        "FVVUVFFRRRUVVVRUUUVFFVVUVFFRRRUVVVRUUUVFFRVVVFFRRRUVVVRUUUVFFRVVVFFRRRUVVVRUUUVFFRVVFFFRUVFRUUVFRUVFRUUVFRUVFRVV" +
        "VFRUVFRUUVFRUVFRRUVFRUVFFRUVFRUVVVRUVFRUVFFRUVFRUVFFRUVFRUUVFRUVFRVVVFRUVFRUUVFRUVFRRUVFRUVFFRUVFRUVFVVUVFRUVFRR" +
        "UVFRUVFFRUVFRUUVFRUVFRVVVFRUVFRUUVFRUVFRRUVFRUVFRRUVFRUVFVVUVFRUVFRRUVFRUVFFRUVFRUUVFRUVFRVVVFRUVFRUUVFRUVFRUUVF" +
        "RUVFRRUVFRUVFVVUVFRUVFRRUVFRUVFFRUVFRUUVFRUVFRUVVVRUVFRUVFFRUVFRUUVFRUVFRRUVFRUVFVVUVFRUVBRUVFRUFBUVFRVFRUVFRVFR" +
        "UVFRVFRUFBUVFRVFRUVFRVFRUVFRVFRUVBQVFRVFRUVFRVFRUVFRVFRUVBQVFRUVRUVFRUVRUVFRVFRUVBQVFRUVRUVFRUVRUVFRUVRUVBQVFRUV" +
        "RUVFRUVRUVFRUVRUVFQUFRUVFUVFRUVRUVFRUVRUVFQUFRUVFUVFRUVFUVFRUVFUVFQUFRUVFUVFRUVFUVFRUVFUVFRUFBUVFUVFRUVFUVFRUVFU" +
        "VFRUFBUVFRVFRUVFRVFRUVFUVFRUFBUVFRVFRUVFRVFRUVFRVFRUFBUVFRVFRUVFRVFRUVFRVFRUVBQVFRUVRUVFRVFRUVERVBQVRUVRUVQUFUVF" +
        "UVFUFBVFRVFUFBVFRVFRVBQVRUVRUVQUFUVFUVFUFBVFUVFUFBVFRVFRVBQVRUVRUVQUFUVFUVFUFEVFUVFUFBVFRVFRVBQVRUVRUVQUFUVFUVEU" +
        "FUVFUVFUFBVFRVFRVBQVRUVRUVQUFUVFUVEUFUVFUVFUFBVFRVFRVBQVRUVRUVQUFUVFUVQUFUVFUVFUFBVFRVFRVBQVRUVRUVQUFUVRUVQUFUVF" +
        "UVFUFBVFRVFRVBQVRUVRUVQURUVRUVQUFUVFUVFUFBVFRVFRVBQVRUVRURQVRUVRUVQUFUVFUVFUFBVFRVFRVBQVRUVRURQVRUVREUVRVBRFRVEU" +
        "FUVRVBRFUVEURUVRFBVFUVEURUVRFBVFUVQURVFRFEVFUVQURVFRFEVFURQVRVFUFEVRURQVRVFUFEVRURRFRVEUFUVRVBRFRVEUFUVRVBRFUVEU" +
        "RUVRFBVFUVEURUVRFBVFUVQURVFRFBVFUVQURVFRFEVFURQVRVFUFEVFURQVRVFUFEVRURRFRVEUFUVRURRFRVEUFUVRVBRFUVEURUVRVBRFUVEU" +
        "RUVRFBVFUVQURVFRFBVFUVQURVFRFEVFURQVRVFUFEVFURQVRVFUFEVRURRFRVEUFUVRURRFRVEUFUVRVBRFUVEUFUVRVBRFUVEURUVRFBUURVFR" +
        "FEVRFEVRFEVRFBVFURRFURRFURRFUVEURVEURVEURVEURUVRFEVRFEVRFEVRVBRFURRFURRFURRFRVEURVEURVEURVFUFEVRFEVRFEVRFEVFURRF" +
        "URRFURRFURQVRVEURVEURVEURVFRFEVRFEVRFEVRFBVFURRFURRFURRFUVEURVEURVEURVEUFUVRFEVRFEVRFEVRURRFURRFURRFURRFRVEURVEU" +
        "RVEURVFUFEVRFEVRFEVRFEVFURRFURRFURRFUVQURVEURVEURVEURUVRFEVRFEVRFEVRFBVFURRFURRFURRFUVEURVEURVEURVEUFUVRFEVRFEUR" +
        "URRFEUVRFEVRFFEURVEURRFFURRFURRFFEVRFEVRRFEURVEURRRFURRFURRRFEVRFEURRVEURVEUURRFURRFEUVRFEVRFEUURVEURVFEURRFURRF" +
        "FEVRFEVRFFEURVEURRFFURRFURRRFEVRFEVRRFEURVEURRRFURRFUURRFEVRFEURRVEURVEUURRFURRFEUVRFEVRFEUURVEURVFEURRFURRFFEVR" +
        "FEVRFFEURVEURRFFURRFURRRFEVRFEURRVEURVEURRRFURRFUURRFEVRFEUURVEURVEUURRFURRFEUVRFEVRFFEURVEURVFEURRFURRFFEVRFEVR" +
        "RFEURUVRRFEUURRFFEURRVFEUURRFFEURRRFEUVRRFFEURRRFEUURRFFUURRFFEUURRFFEURRVFEURRRFFEURRRFEUVRRFEUURRFFEUURRFFUURR" +
        "FFEURRRFFEURRVFEURRRFEUURRFFEUVRRFEUURRFFEURRRFFUURRFFEURRRFEUURRVFEURRRFEUURRFFUURRRFEUURRFFEURRVFEUURRFFEURRRF" +
        "EUVRRFEUURRRFEUURRFFUURRFFEUURRFFEURRVFEURRRFEUURRRFEUVRRFEUURRFFEUURRFFUURRFFEURRRFEUURRVFEURRRFEUURRFFEUVRRFEU" +
        "URRFFEURRVFFEUURRRFFFEUURRRRFFEUUURRRFFEEUURRRFFFEUURRRRFFEUUURRRFFEEUURRRFFFEUURRRRFFEUUURRRFFEEUURRRFFFEUURRRR" +
        "FFEUUURRRFFEEUURRRFFFEUURRRRFFEUUURRRFFEEUURRRFFFEUURRRRFFEUUURRRFFEEUURRRFFEUUURRRFFFEUURRRRFFEUUQRRRFFEUUURRRF" +
        "FFEUURRRRFFEUUQRRRFFEUUURRRFFFEUURRRRFFEUUQRRRFFEUUURRRFFFEUURRRRFFEUUQRRRFFEUUURRRFFFEUURRRRFFEUUQRRRFFEUUURRRF" +
        "FFEUURRRRFFEUUQREUUUUUQRRRFFFFFEEUUUUUQRRRRRFFFEEUUUUUQRRRRRRBFFEUUUUUQRRRRRRBFFFFEUUUQRRRRRRBFFFFFEEUURRRRRRBFF" +
        "FFFEEUUURRRRRBFFFFFEEUUUUURRRBFFFFFEEUUUUUQRRRRFFFFEEUUUUUQRRRRRRFFEEUUUUUQRRRRRRBFFEUUUUUQRRRRRRBFFFFEUUUQRRRRR" +
        "RBFFFFFEEUURRRRRRBFFFFFEEUUUURRRRBFFFFFEEUUUUUQRRRFFFFFEEUUUUUQRRRRFFFFEEUUUUUQRRRRRRFFEEUUUUUQRRRRRRBFFFEUUUUQR" +
        "RRRRRBFFFFFEUUQRRRRRBFFEEVFEEUVEEUUUEUUUUUQUUUQRUUQRRUQRRRQRRRQRRRRRRBRRRBFRRBFFRBFFFBFFFFFEFFFEEVFEEUVEEUUUEUUU" +
        "UUQUUUQRUUQRUUQRRUQRRRQRRRRRRBRRRBFRRBFFRBFFFBFFFFFEFFFEEVFEEUVEEUVEEUUUEUUUUUQUUUQRUUQRRUQRRRQRRRRRRBRRRBFRRBFF" +
        "RBFFFBFFFBFFFFFEFFFEEVFEEUVEEUUUEUUUUUQUUUQRUUQRRUQRRRQRRRRRRBRRRBFRRBFRRBFFRBFFFBFFFFFEFFFEEVFEEUVEEUUUEUUUUUQU" +
        "UUQRUUQRRUQRRUQRRRQRRRRRRBREEVFEFBFFRBFRRBFRRBQRRUQRUUQUEUVEEVFEFBFFRBFRRBQRRUQRUUQUEUVEEVFEFBFFRBFFRBFRRBQRRUQR" +
        "UUQUEUVEEVFEFBFFRBFRRBQRRUQRUUQUEUVEEVFEFBFFFBFFRBFRRBQRRUQRUUQUEUVEEVFEFBFFRBFRRBQRRUQRUUQUEUVEEVFEEVFEFBFFRBFR" +
        "RBQRRUQRUUQUEUVEEVFEFBFFRBFRRBQRRUQRUUQUEUVEEUVEEVFEFBFFRBFRRBQRRUQRUUQUEUVEEVFEFBFFRBFRRBQRRUQRUUQUEUUUEUVEEVFE" +
        "FBFFRBFRRBQRRUQRUUQUEUVEEVFEFBFFERFFRBQRUUREERFFRBERRUQUEVFERBERRUQUEVFERBERRUQUEVFEFBFRREQREUVEFBFRREQREUVEFBFR" +
        "REQREUVEERFFRBQRUUREERFFRBQRUUREERFFRBQRRUQUEVFERBERRUQUEVFERBERRUQUEVFERBFRREQREUVEFBFRREQREUVEFBFRREQREUVEERFF" +
        "RBQRUUREERFFRBQRUUREERFFRBQRUUQUEVFERBERRUQUEVFERBERRUQUEVFERBERRUQREUVEFBFRREQREUVEFBFRREQREUVEFBFFRBQRUUREERFF" +
        "RBQRUUREERFFRBQRUUREEVFERBERRUQUEVFERBFFREQREVFERBQREVFERBQREUVERBERUUREFBERRUREERFRREQUERFFREQREVFERBQREUVERBQR" +
        "EUVERBERUUREFBERRUREERFRREQUERFFREQREVFERBQREUVERBEREUVERBERUUREFBERRUREERFRREQUERFFREQREVFERBQREUVERBERUUREFBER" +
        "UUREFBERRUREERFRREQUERFFREQREVFERBQREUVERBERUUREFBERRUREFBERRUREERFRREQUERFFREQREVFERBQREUVERBERUUREFBERRUREERER" +
        "RUREERFRREQUERFFREQREVFERBQREUVERBERUUREFBEREUVEREQUERERUUREREQRERERRURERBQRERFRRERERBERERFFREREFBEREVFEREREERER" +
        "EUVEREQUERERUUREREQRERERRURERBQRERFRRERERBERERFFREREFBERERFFREREFBEREVFEREREEREREUVEREQUERERUUREREQRERERRURERBQR" +
        "ERFRRERERBERERFFREREFBEREVFEREREEREREUVEREQUERERUUREREQRERERRURERBQRERFRRERERBERERFFREREFBEREVFEREREEREREUVEREQU" +
        "EREREUVEREQUERERUUREREQRERERRURERBQRERFRRERERBFRRURERERERBERERERERFFREREREREFBEREREREUVEREREREQUERERERERUURERERE" +
        "REQRERERERFRRERERERERBERERERERFFREREREREEREREREREUVEREREREQUERERERERUURERERERBQRERERERFRRERERERERBERERERERFFRERE" +
        "REREEREREREREUVEREREREQUERERERERRURERERERBQRERERERFRRERERERERBEREREREVFEREREREREEREREREREUVEREREREQRERERERERRURE" +
        "RERERBQRERERERFRREREREREFBEREREREVFEREREREREERERERERUREREREREREREREREREREREREREREUVERERERERERERERERERERERERERBQR" +
        "ERERERERERERERERERERERERERFFREREREREREREREREREREREREREQUERERERERERERERERERERERERERFRRERERERERERERERERERERERERERE" +
        "ERERERERERERERERERERERERERERRUREREREREREREREREREREREREREFBEREREREREREREREREREREREREREUVERERERERERERERERERERERERE" +
        "RBQREREREREREREREREREREREREREVFERERERERERERERERERERERERERISqqqpqqqqqqqqmqqqqqqqpqqqqqpqqqqqqqqmqqqqqmqqqqqqqpqqq" +
        "qqpqqqqqqqqmqqqqqqqpqqqqqpqqqqqqqqmqqqqqmqqqqqqqpqqqqqpqqqqqqqqmqqqqqmqqqqqqqpqqqqqqqqmqqqqqmqqqqqqqqaqqqqpqqqqq" +
        "qqqmqqqqqmqqqqqqqqaqqqqqqqmqqqqqmqqqqqqqqaqqqqqaqqqqqqqmqqqqqmqqqqqqqqaqqqqqqqmqqqqqmqqqqqqqqaqqqqqaqqqqqqqmqqqq" +
        "qmqqqqqqqqaqqqqqaqqqqqqqmqqqqqqqqaqqqqqaqqqqqqqpqqqqqmqqqqqqqqaqqqlqqmqqmqqaqqaqpqqpaqpqqpqqmqqmqqaqqWqqaqqaqpqq" +
        "pqqpqqlqqmqqmqqaqqaqqaqpaqpqqpqqmqqmqqmqqWqqaqqaqqaqpqqpqqlqqmqqmqqmqqaqqaqpaqqaqpqqpqqmqqmqqWqqmqqaqqaqpqqpqqlq" +
        "qpqqmqqmqqaqqWqqaqqaqpqqpqqmqqlqqmqqmqqaqqaqpqqpaqpqqpqqmqqmqqmqqWqqaqqaqpqqpqqpqqlqqmqqmqqaqqaqqaqpaqpqqpqqpqqm" +
        "qqmqqWqqaqqaqqaqpqqpqqlqqpqqmqqmqqaqqaqpaqqaqpqqpqqmqqmqqWqqmqqaqqaqtppqaqqpppqaaqqpqaaammqqqammmmpqqqmmpppqaqqp" +
        "ppqaaqqpqaaammqqqaammmpqqqmmpppqaqqpppqaaqqpqaaammqqqaammmpqqqmmpppqqqmpppqaaqqpqaaammqqqaammmpqqqmmpppqqqmpppqa" +
        "aqqpqaaaamqqqaammmpqqqmmmppqqqmpppqaaqqpqaaaamqqqaammmpqqqmmmppqqqmpppqaaqqppqaaamqqqaammmpqqqmmmppqqqmpppqaaqqp" +
        "pqaaamqqqaammmqqqammmppqqqmpppqaaqqppqaaamqqqaammmqqqammmppqqqmppppqaqqpppapaWqamqamqWlqmpqmqWlqmpqmpqlpapqapqap" +
        "aWqamqamqWlqmqamqWlqmpqmpqlpapqapqapaWqamqamqWmamqamqWlqmpqmpqlpapqapqapaWqamqamqWmamqamqWlqmpqmpqlpapqapqapaWqa" +
        "mqamaWqamqamqWlqmpqmpqlpapqapqapaWqamqapaWqamqamqWlqmpqmpqlpapqapqapaWqapqapaWqamqamqWlqmpqmpqlpapqapqapaZqapqap" +
        "aWqamqamqWlqmpqmpqlpapqapqapaZqapqapaWqamqamqWlqmpqmpqlpapqapqZpapqapqapaWqamqaWaaZpmmaapmmmaZpmmqZppmmaZpqmaaZp" +
        "mmaapmmmaZpmmqZppmmaZpqmaaZpmmaapmmmaZpmmqZppmmaZpqmmaZpmmmappmmaZppmqaZpmmaaZqmmaZpmmmappmmaZppmqaZpmmaaZqmmaZp" +
        "mmmappmmaZppmqaZpmmaaZqmmaZppmmaZpqmaaZpmmaapmmmaZpmmqZppmmaZpqmaaZpmmaapmmmaZpmmqZppmmaZpqmaaZpmmaapmmmaZpmmqaZ" +
        "pmmaaZqmmaZpmmmappmmaZppmqaZpmmaaZqmmaZpmmmappmmaZppmqaZpmmaaZqmmaZpmmmappmmaZppmqaZZqaZZqaZaWaamWaamWammWmmmWlm" +
        "mplmpplmpplpZpqZZpqZZqaZaaaZaWaamWammWammWlmmmlmmplmpplppplpZpqZZpqZZqaZaWaaaWaamWammWmmmWlmmplmmplmpplpZpppZpqZ" +
        "ZqaZZqaZaWaamWaamWammWlmmmlmmplmpplmpplpZpqZZpqZZqaZaaaZaWaamWammWammWlmmplmmplmpplppplpZpqZZqaZZqaZaWaaaWaamWam" +
        "mWmmmWlmmplmmplmpplpZpppZpqZZqaZaaaZaWaamWaamWammWlmmmlmmplmpplmpplpZpqZZpqZZqaZaWaaaWaamaaZmZmZaWZmZmZmZmZmmpmZ" +
        "mZmZmZmZaWZmZmZmZmZmppmZmZmZmZmZmWZmZmZmZmZmZpqZmZmZmZmZmWZmZmZmZmZmZpqZmZmZmZmZmWlmZmZmZmZmZqaZmZmZmZmZmZlmZmZm" +
        "ZmZmZqaZmZmZmZmZmZlmZmZmZmZmZmaamZmZmZmZmZlpZmZmZmZmZmaamZmZmZmZmZlpZmZmZmZmZmammZmZmZmZmZmZZmZmZmZmZmZmmpmZmZmZ" +
        "mZmZZmZmZmZmZmZmmpmZmZmZmZmZaWZmZmZmZmZmppmZmZmZmZmZmWZmZmZmZmZmppmZmZmZmZmZmWZmZmZmZmZmZpqZmZmpmWVmZpaZmWVmZpaZ" +
        "mWVmZpaZmVlmZpaZmVlmZpaZmVlmZmaZmVlmZmaZmVlmZmaZmZllZmaZmZllZmaZmZllZmaWmZllZmaWmZllZmaWmZlZZmaWmZlZZmaWmZlZZmaW" +
        "mZlZZmZmmZlZZmZmmZlZZmZmmZmZZWZmmZmZZWZmmZmZZWZmlpmZZWZmlpmZZWZmlpmZWWZmlpmZWWZmlpmZWWZmZpmZWWZmZpmZWWZmZpmZmWVm" +
        "ZpmZmWVmZpmZmWVmZpaZmWVmZpaZmWVmZpaZmVlmZpaZmVlmZpaZmVlmZpaZmVlmZmaZmVlmZmaZmVlmZmaZmZllZmaZmZllZmaZWWaZZZZZZpZZ" +
        "ZplllllmmWWWmWWWWWaZZZZZZpllZplllllmmWWWWWaZWWaZZZZZZplllllmlllmmWWWWWaZZZaZZZZZZplllllmmVlmmWWWWWaZZZZZZpZZZpll" +
        "lllmmWWWmWWWWWaZZZZZZpllZplllllmmWWWWWaZWWaZZZZZZplllllmlllmmWWWWWaZZZaZZZZZZplllllmmWVmmWWWWWaZZZZZZplZZplllllm" +
        "mWWWWWaWWWaZZZZZZplllplllllmmWWWWWaZWWaZZZZZZplllllmlllmmWWWWWaZZZaZZZZZZplllllmmWVmmWWWWWaZZZZZZplZZplllpllWZZZ" +
        "lmWZZVmWZZZlWZZZlmVZZlmWZZllWZZllmVZllmWZZllWZZllmVZllmWZVlmWZZlmWVZlmWWZVlmWZZlmWVZlmWWZVmWWZZlWWZZlmWZZVmWWZZl" +
        "WWZZlmWZZVmWZZZlWZZZlmVZZlmWZZZlWZZZlmVZZlmWZZllWZZllmVZllmWZZllWZZllmVZllmWZVlmWZZlmWVZlmWWZVmWWZZlmWVZlmWWZVmW" +
        "WZZlWWZZlmWZZVmWZZZlWWZZlmWZZVmWZZZlWZZZlmVZZlmWZZllWZZZlmVZZlmWZZllWZZllmVZllmWZVlmWZZllmVZllmWZVlmWZZlmWVZlmVm" +
        "WZaVZVlZlmVlWZaVZVlWlmVZWZZlZVlWlmVZWZZlZVmWlWVZVpZlWVmWlWVZVpZlWVmWZWVZlpVlWVaWZWVZlpVlWVaWZVlZlmVlWZaVZVlZlmVl" +
        "WZaVZVlWlmVZWZaVZVlWlmVZWZZlZVmWlWVZVpZlZVmWlWVZVpZlWVmWZWVZlpVlWVmWZWVZlpVlWVaWZVlZlmVlWVaWZVlZlmVlWZaVZVlWlmVZ" +
        "WZaVZVlWlmVZWZZlZVmWlWVZVpZlZVmWlWVZVpZlWVmWZWVZlpVlWVmWZWVZlpVlWVaWZVlZlpVlWVaWZVlZlmVlWZaVZVlWlmVlWZaVZVlWlmVZ" +
        "WZZlhWVlZWVZWVlZWVZWVlaWlZWVlWVlZWVlWVlZWVZWVlaWlZWVlWVlZWVlWVlZWVlWVlZWlpWVlWVlZWVlWVlZWVlWVlZWlpWVlZVlZWVlWVlZ" +
        "WVlWVlZWlpWVlZVlZWVlZVlZWVlZVlZWlpWVlZVlZWVlZVlZWVlZVlZWVpaVlZWVZWVlZVlZWVlZVlZWVpaVlZWVZWVlZWVZWVlZVlZWVpaVlZWV" +
        "ZWVlZWVZWVlZWVZWVlaWlZWVZWVlZWVZWVlZWVZWVlaWlZWVlWVlZWVZWVlZWVZWVlaWlZWVlWVlZWVlWVlZWVlWVlaWlZWVlWVlZWVlWVlZWVlW" +
        "VlZWlpWVlUVZWWVllZVVVlZZZWWVlVVWVllZZWWVlVVWVlllZZWVVVZWWVllZZWVVVZWWVlllZVVVlZZWWVllZVVVlZZWWWVlVVWVllZZWWVlVVW" +
        "VllZZWWVVVZWWVllZZWVVVZWWVllZZWVVVZZWWVllZVVVlZZWWVllZVVVllZZWWVlVVWVllZZWWVlVVWVlllZZWVVVZWWVllZZWVVVZWWWVllZVV" +
        "VlZZWWVllZVVVlZZWWWVlVVWVllZZWWVlVVWVllZZZWVVVZWWVllZZWVVVZWWVllZZVVVlZZWWVllZVVVlZZWWVllZVVVllZZWWVlVVWVllZZWWV" +
        "lVVWWVllZZWVVVZWWZVVWWVVVlmVVVllVVZllVVZZVVWZZVVWZVVVmWVVVmVVVZlVVZZlVVWZVVWWZVVWWVVVlmVVVllVVZllVVZlVVWZZVVWZVV" +
        "VmVVVlmVVVZlVVZZlVVZZVVWWZVVWWVVVmWVVVllVVZllVVZlVVWZZVVWZVVVmVVVlmVVVZlVVZZlVVZZVVWWZVVWWVVVmWVVVllVVZllVVZlVVW" +
        "ZZVVWZVVVmVVVlmVVVZlVVZZlVVZZVVWWZVVWWVVVmWVVVmVVVZllVVZlVVWZVVWWZVVVmVVVlmVVVllVVZZlVVZZVVWZZVVWWVVVmWVVVmVVVZl" +
        "lVVZlVVWZVVWWZVVVmVVZlVWlVVlVVlVVpVVZVVZVVaVVWVVWVVWlVVlVVlVVpVVZVVZVVaVVWVVWVVWlVVlVVlVVpVVZVVZVVaVVWVVWVVWlVVl" +
        "VVlVVpVVZVVZVVaVVWVVWVVWlVVlVVlVVpVVlVVlVVlVVpVVZVVZVVaVVWVVWVVWlVVlVVlVVpVVZVVZVVaVVWVVWVVWlVVlVVlVVpVVZVVZVVaV" +
        "VWVVWVVWlVVlVVlVVpVVZVVZVVaVVWVVWVVWlVVlVVlVVpVVZVVZVVaVVWVVWVVWlVVlVVlVVpVVZVVZVVaVVWVVWVVWlVWVVWVVWVVWlVVlVVlV" +
        "VpVVZVVZVVaVVWVVWVVWlVVlVUlVWVWVVVVWVVlVlVVVVlVZVZVVVVZVWVWVVVVWVVlVlVVVVlVZVWVVVVZVWVVlVVVWVVlVZVVVVlVZVWVVVVZV" +
        "WVVlVZVVVVlVZVWVVVVZVWVVlVVVWVVlVZVVVVlVZVWVVVVWVWVVlVVVVlVlVZVVVVZVZVWVVVVWVWVVlVVVVlVZVZVVVVZVWVWVVVVWVVlVlVVV" +
        "VlVZVZVVVVZVWVWVVVVWVVlVZVVVVlVZVWVVVVZVWVVlVVVWVVlVZVVVVlVZVWVVlVVVWVVlVZVVVVlVZVWVVVVZVWVVlVVVWVVlVZVVVVZVZVWV" +
        "VVVWVWVVlVVVVlVlVZVVVVZVZVWVVVVGVVVZVVWVVVVVWVVVZVVVVVZVVWVVVVVWVVVlVVVVVlVVWVVVlVVVVVlVVZVVVVVZVVWVVVVVVlVVZVVV" +
        "VVZVVWVVVVVWVVVlVVWVVVVVWVVVlVVVVVlVVZVVVVVZVVWVVVVVVlVVZVVVVVZVVWVVVVVWVVVlVVWVVVVVWVVVlVVVVVlVVZVVVVVZVVVlVVVV" +
        "VlVVZVVVVVZVVWVVVVVWVVVZVVWVVVVVWVVVlVVVVVlVVZVVVVVWVVVlVVVVVlVVZVVVVVZVVWVVVZVVVVVZVVWVVVVVWVVVlVVVVVlVVZVVVVVW" +
        "VVVlVVVVVlVVZVVVVVZVVWVVVZVVVVVZVVWVRVVVVVVZVVVVVVVZVVVVVVVlVVVVVVVlVVVVVVVlVVVVVVWVVVVVVVWVVVVVVVWVVVVVVVVVVlVV" +
        "VVVVVlVVVVVVWVVVVVVVWVVVVVVVWVVVVVVVZVVVVVVVZVVVVVVVlVVVVVVVlVVVVVVVlVVVVVVVVVZVVVVVVVZVVVVVVVZVVVVVVVlVVVVVVVlV" +
        "VVVVVWVVVVVVVWVVVVVVVWVVVVVVVZVVVVVVVZVVVVVVVZVVVVVVVVVWVVVVVVVWVVVVVVVZVVVVVVVZVVVVVVVZVVVVVVVlVVVVVVVlVVVVVVWV" +
        "VVVVVVWVVVVVVVWVVVVVVVVVVlVVVVVVVlVVVVVVVkVVVVVVVVVVVVVVVVVVVVVVVVWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWVVVVVVVVVV" +
        "VVVVVVVVVVVVVVVVVVVVVVVVVlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVZVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWVVVVVVVVVVVVVVVVVVV" +
        "VVVVVVVVVVVVVZVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVZVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWVVVVVVVVVVVVVVVVVVVVVVVVVVVV" +
        "VVVVlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVZVVVVVVVFVVVVVVVVVVVVVVVRVVVVVVVVVVVVVVVUVVVVVVVVVVVVVUVVVVVVVVVVVVVVVVFV" +
        "VVVVVVVVVVVVFVVVVVVVVVVVVVVVRVVVVVVVVVVVVVVVVFVVVVVVVVVVVVUVVVVVVVVVVVVVVVVRVVVVVVVVVVVVVVVUVVVVVVVVVVVVVUVVVVVV" +
        "VVVVVVVVVVFVVVVVVVVVVVVVVVRVVVVVVVVVVVVVRVVVVVVVVVVVVVVVUVVVVVVVVVVVVVUVVVVVVVVVVVVVVVVFVVVVVVVVVVVVVVVUVVVVVVVV" +
        "VVVVVRVVVVVVVVVVVVVVVVFVVVVVVVVVVVVVVVRVVVVVVVVVVVVVVVVVVUVVVVVVRVVVVVUVVVVVVRVVVVVVVVRVVVVVVFVVVVVRVVVVVVFVVVVV" +
        "RVVVVVVFVVVVVRVVVVVVFVVVVVVVVFVVVVVUVVVVVVFVVVVVUVVVVVVFVVVVVUVVVVVVRVVVVVUVVVVVVRVVVVVVVVRVVVVVVFVVVVVRVVVVVVFV" +
        "VVVVRVVVVVVFVVVVVRVVVVVVFVVVVVVVVFVVVVVUVVVVVVFVVVVVUVVVVVVFVVVVVUVVVVVVFVVVVVUVVVVVVVVUVVVVVVRVVVVVUVVVVVVRVVVV" +
        "VUVVVVVVRVVVVVVFVVVVVRVVVVVVFVVVVVVVVFVVVVVUVVVVVVFVVVVVUWVFVVUVVVVVVFVVUVVVRVVVFVVVVVFVVUVVVRVVVVVUVVVRVVVFVVUV" +
        "VVVVVFVVRVVVFVVVVVRVVVFVVUVVVRVVVVVUVVVRVVUVVVVVVFVVUVVVRVVVFVVVVVRVVVFVVUVVVVVUVVVRVVVFVVUVVVVVVFVVUVVVRVVVVVRV" +
        "VVFVVUVVVRVVVVVUVVVRVVVFVVUVVVVVUVVVRVVVFVVVVVRVVVFVVUVVVRVVVVVUVVVFVVUVVVVVVFVVUVVVRVVVFVVVVVRVVVFVVRVVVVVUVVVR" +
        "VVVFVVUVVVVVVFVVUVVVRVVVVVRVVVFVVUVVVRVVVVVUVVVRVVVFVVVVVFVVUVVVVVVRVRVVVVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVV" +
        "VVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVVV" +
        "VFVFVVVUVUVVVVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVVVVFVVVRVRVVVVFVFVVVU" +
        "VUVVVVRVRVVVVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVVVVFVFVVVUVUVVVVRVRVFVUVVRVVFVUVVRVVFVUVVFVUVVRVVFVUVVRVVFVUVV" +
        "FVUVVRVVFVUVVRVVFVUVVVVUVVRVVFVUVVRVVFVUVVRVUVVRVVFVUVVRVVFVUVVRVUVVRVVFVUVVRVVFVUVVRVUVVRVVFVUVVRVVFVUVVVVUVVRV" +
        "VFVUVVRVVFVUVVRVUVVRVVFVUVVRVVFVUVVRVUVVRVVFVUVVRVVFVUVVRVUVVRVVFVUVVRVVFVUVVRVVVVRVVFVUVVRVVFVUVVRVVFVRVVFVUVVR" +
        "VVFVUVVRVVFVRVVFVUVVRVVFVUVVRVVFVRVVFVUVVRVVFVUVVRVVVVRVVFVUVVRVVFVUVVRVVEVUFVVFVVFVVEVVUVVUFVVFVVQVVUVVUVVUFVVR" +
        "VVQVVUVVUVVURVVRVVQVVUVVURVVRVVRVVQVVVFVVBVVRVVRVVRFVVFVVBVVRVVRFVVFVVFVVBVVRVVUFVVFVVFVVEVVUVVUFVVFVVEVVUVVUVVU" +
        "FVVFVVQVVUVVUVVUFVVRVVQVVUVVUVVURVVRVVQVVUVVVBVVRVVRVVQVVVFVVBVVRVVRVVRFVVFVVBVVRVVRFVVFVVFVVBVVUVVUFVVFVVFVVEVV" +
        "UVVUFVVFVVEVVUVVUVVUFVVFVVQVVUVVUVVURVVRVVQVVUVVURVVRVVRVVQVVUVVVBVVRVVRVVQVVVFFVEVVVEVVVFEVVVEVVVEVVVEVVVRFVVRF" +
        "VVRFVVRFVVRRFVVRFVVRFVVRFVVRRVVURVVURVVURVVUURVVURVVURVVURVVUUVVVEVVVEVVVEVVVEUVVVEVVVEVVVEVVVFFVVRFVVRFVVRFVVRF" +
        "FVVRFVVRFVVRFVVRFVVURVVURVVURVVURVVUURVVURVVURVVURVVVEVVVEVVVEVVVEVVVFEVVVEVVVEVVVEVVVFFVVRFVVRFVVRFVVRRFVVRFVVR" +
        "FVVRFVVRRVVURVVURVVURVVURRVVURVVURVVURVVUUVVVEVVVEVVVEVVVEUVVVEVVVEVVVEVVVEVVVRFVVRFRVFFVVRRRVVUUUUVVVFFFVVURRVV" +
        "VEUVVVRRFVVUURVVVFFFVVRRRRVVUUUVVVFFFVVURRVVVEUVVVRRFVVUUUVVVFFFVVRRRRVVUUUVVVFFFVVURRVVVEUVVVRRFVVUUUVVVFFFVVRR" +
        "RRVVUUUVVVFFFVVURRVVVFEVVVRRFVVUUUVVVFFFVVRRRRVVUUUVVVRFFVVURRVVVFEVVVRRFVVUUUVVVFFFFVVRRRVVUUUVVVRFFVVURRVVVFEV" +
        "VVRRRVVUUUVVVFFFFVVRRRVVUUUVVVRFFVVURRVVVFEVVVRRRVVUUUVVVFFFFVVRRRVVUUUVVVRFFVVUURVVVFEVVVRRRUUVVVRUUUVFFVVUUVFF" +
        "FRVVVFFRRRUVVVRRRUUVVVRUUUVFFVVUUVFFFRVVVFFRRRVVVFRRRUUVVVRUUUVFFVVUUVFFFRVVVFFRRRVVVFRRRUUVVVRUUUUVFVVUUVFFFRVV" +
        "VFFFRRVVVFRRRUUVVVRUUUUVFVVUUVFFFRVVVFFFRRVVVFRRRUUVVVRRUUUVFVVUUVFFFRVVVFFFRRVVVFRRRUUVVVRRUUUVFVVUUVFFFVVUVFFF" +
        "RRVVVFRRRUUVVVRRUUUVFVVUUVFFFVVUVFFFRRVVVFRRRRUVVVRRUUUVFVVUUUVFFVVUVFFFRRVVVFRRRRUVVVRRUUUVFVV0VFRUVFFRUUVFRRUV" +
        "FVVUVFRUUVFRRUVFFRUVFVVUVFRRUVFFRUVFFRUVVVRUVFFRUVFFRUUVFRVVVFRUUVFRUUVFRRUVFVVUVFRUUVFRRUVFFRUVFVVUVFRRUVFFRUVF" +
        "FRUVVVRUVFFRUUVFRUUVFRVVVFRUUVFRUUVFRRUVFVVUVFRUUVFRRUVFFRUVVVRUVFRRUVFFRUUVFRUVVVRUVFFRUUVFRUUVFRVVVFRUUVFRUUVF" +
        "RRUVFVVUVFRRUVFRRUVFFRUVVVRUVFRRUVFFRUUVFRUVVVRUVFFRUUVFRUUVFRVVVFRUUVFRRUVFRRUVFVVUVFRRUVFRRUVFFRUVVVFRUVFRUVFR" +
        "UVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUV" +
        "FRUVVVRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFFRUVFRUVFRUVFRUVFRUVF" +
        "RUVFRUVFRUVFRUVFRUVFRRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRVVVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVBQVFRVF" +
        "RUVFUVFRUVRUFBUVFUVFRUVRUVFRVFRUFBUVRUVFRVFRUVFUVFQUFRUVRUVFRVFRUVRUVBQVFRVFRUVFUVFRUVRUFBUVFUVFRUVRUVFRVFRUFBUV" +
        "RUVFRVFRUVFUVFQUFRUVRUVFUVFRUVRUVBQVFRVFRUVFUVFRVFRUFBUVFUVFRUVRUVFRVFQUFRUVRUVFRVFRUVFUVFQUFRVFRUVFUVFRUVRUVBQV" +
        "FRVFRUVFUVFRVFRUFBUVFUVFRUVRUVFRVFQUFRUVRUVFRVFRUVFUVFQUFRVFRUVFUVFRUVRUVBQVFRVFRUVRUVFRVFRUFBUVFUVFRUVRUVFUVFRE" +
        "VBQVRUVRUVFUFBVFRVFRVBQVRUVRUVFUFBVFRVFRVBQVRUVFUVFUFBVFRVFRVBQVRUVFUVFUFBVFRVFRVBQVRUVFUVFUFBVFRVFRVBQVFUVFUVFU" +
        "FBVFRVFRVBQVFUVFUVFUFBVFRVFRVFQUFUVFUVFUFBVFRVFRVFQUFUVFUVFUFBVFRVFRUVQUFUVFUVFUFBVFRVFRUVQUFUVFUVFUFBVFRUVRUVQU" +
        "FUVFUVFUFBVFRUVRUVQUFUVFUVFUFBVFRUVRUVQUFUVFUVFUFBUVRUVRUVQUFUVFUVFUFBUVRUVRUVQUFUVFUVFUVBQVRUVRUVQUFUVFUVFUVBQV" +
        "RUVRAQ==";
}
